"""Bidding & Contracts routes (Phase 4) embedded in the gateway."""

import io
import logging
import uuid
from datetime import UTC, datetime
from datetime import date as date_type
from decimal import Decimal

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    Query,
    Request,
    status,
)
from fastapi.responses import StreamingResponse
from fpdf import FPDF
from pydantic import BaseModel, Field
from sqlalchemy import func, or_, select, text, update
from sqlalchemy.ext.asyncio import AsyncSession

from shared.database import get_db
from shared.events import publish_event

from ..deps import get_current_user, get_optional_user
from ..models_bidding import Bid, Contract, ContractSignature, JobPost

logger = logging.getLogger(__name__)

router = APIRouter(tags=["bidding"])

# ---------------------------------------------------------------------------
# State machines
# ---------------------------------------------------------------------------
JOB_POST_TRANSITIONS = {
    "open": {"bidding_closed", "cancelled"},
    "bidding_closed": {"awarded"},
    "awarded": {"in_progress"},
    "in_progress": {"completed"},
}

BID_HIRER_TRANSITIONS = {
    "submitted": {"shortlisted", "accepted", "rejected"},
    "shortlisted": {"accepted", "rejected"},
}

BID_PROVIDER_TRANSITIONS = {
    "submitted": {"withdrawn"},
}

CONTRACT_LEGAL_TEMPLATE = """\
INDEPENDENT SERVICE PROVIDER AGREEMENT

This Service Agreement ("Agreement") is entered into through the Jobsy Platform on {date}.

1. PARTIES
   Client: {hirer_name} ("Client")
   Service Provider: {provider_name} ("Provider")

2. INDEPENDENT CONTRACTOR STATUS
   The Provider is an independent contractor and not an employee of the Client or Jobsy Limited.
   Nothing in this Agreement shall create an employer-employee relationship. The Provider is
   responsible for their own tax obligations including Income Tax and NIS contributions as
   required under the laws of Jamaica.

3. SCOPE OF WORK
   {scope_of_work}

4. COMPENSATION
   The Client agrees to pay the Provider {currency} {amount} for the services described above.
   Payment shall be made through the Jobsy Platform.

5. TIMELINE
   Start Date: {start_date}
   Estimated Completion: {end_date}

6. LOCATION
   {location_text}

7. CANCELLATION
   Either party may cancel this Agreement with written notice through the Jobsy Platform.
   If the Client cancels after work has commenced, the Provider shall be compensated for
   work completed up to the date of cancellation.

8. DISPUTE RESOLUTION
   Any disputes shall first be addressed through the Jobsy Platform's dispute resolution
   process. If unresolved, the parties agree to mediation before pursuing legal action.
   This Agreement shall be governed by and construed in accordance with the laws of Jamaica.

9. LIABILITY
   The Provider shall perform the services with reasonable skill and care. Neither party
   shall be liable for indirect or consequential damages.

10. CONFIDENTIALITY
    Both parties agree to keep confidential any proprietary information disclosed during
    the performance of this Agreement.

11. AMENDMENTS
    This Agreement may only be amended by written consent of both parties through the
    Jobsy Platform.

12. ELECTRONIC EXECUTION
    This Agreement is executed electronically in accordance with the Electronic Transactions
    Act, 2006 of Jamaica. Digital signatures applied through the Jobsy Platform carry the
    same legal effect as handwritten signatures.

Generated by Jobsy Platform
Contract ID: {contract_id}"""


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------
class JobPostCreate(BaseModel):
    title: str = Field(..., max_length=200)
    description: str
    category: str = Field(..., max_length=100)
    subcategory: str | None = None
    required_skills: list[str] = []
    budget_min: Decimal | None = None
    budget_max: Decimal | None = None
    currency: str = Field(default="JMD", max_length=3)
    location_text: str | None = None
    parish: str | None = None
    deadline: str | None = None
    bid_deadline: str | None = None
    attachments: list[str] = []
    visibility: str = Field(default="public")
    max_bids: int | None = None


class JobPostUpdate(BaseModel):
    title: str | None = None
    description: str | None = None
    budget_min: Decimal | None = None
    budget_max: Decimal | None = None
    deadline: str | None = None
    bid_deadline: str | None = None
    max_bids: int | None = None


class BidCreate(BaseModel):
    amount: Decimal = Field(..., gt=0)
    currency: str = Field(default="JMD", max_length=3)
    proposal: str
    estimated_duration_days: int | None = None
    available_start_date: str | None = None
    attachments: list[str] = []


class BidUpdate(BaseModel):
    amount: Decimal | None = Field(default=None, gt=0)
    proposal: str | None = None
    estimated_duration_days: int | None = None
    available_start_date: str | None = None
    attachments: list[str] | None = None


class BidStatusUpdate(BaseModel):
    status: str
    hirer_note: str | None = None


class ContractSign(BaseModel):
    signature_data: str
    signature_method: str = Field(default="digital")


class JobPostStatusUpdate(BaseModel):
    status: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _job_post_response(jp: JobPost) -> dict:
    return {
        "id": jp.id,
        "hirer_id": jp.hirer_id,
        "title": jp.title,
        "description": jp.description,
        "category": jp.category,
        "subcategory": jp.subcategory,
        "required_skills": jp.required_skills or [],
        "budget_min": float(jp.budget_min) if jp.budget_min is not None else None,
        "budget_max": float(jp.budget_max) if jp.budget_max is not None else None,
        "currency": jp.currency,
        "location_text": jp.location_text,
        "parish": jp.parish,
        "latitude": float(jp.latitude) if jp.latitude is not None else None,
        "longitude": float(jp.longitude) if jp.longitude is not None else None,
        "deadline": jp.deadline.isoformat() if jp.deadline else None,
        "bid_deadline": jp.bid_deadline.isoformat() if jp.bid_deadline else None,
        "status": jp.status,
        "attachments": jp.attachments or [],
        "visibility": jp.visibility,
        "max_bids": jp.max_bids,
        "created_at": jp.created_at.isoformat(),
        "updated_at": jp.updated_at.isoformat(),
    }


def _bid_response(b: Bid) -> dict:
    return {
        "id": b.id,
        "job_post_id": b.job_post_id,
        "provider_id": b.provider_id,
        "amount": float(b.amount),
        "currency": b.currency,
        "proposal": b.proposal,
        "estimated_duration_days": b.estimated_duration_days,
        "available_start_date": (
            b.available_start_date.isoformat() if b.available_start_date else None
        ),
        "attachments": b.attachments or [],
        "status": b.status,
        "is_winner": b.is_winner,
        "hirer_note": b.hirer_note,
        "created_at": b.created_at.isoformat(),
        "updated_at": b.updated_at.isoformat(),
    }


def _contract_response(c: Contract) -> dict:
    return {
        "id": c.id,
        "job_post_id": c.job_post_id,
        "bid_id": c.bid_id,
        "hirer_id": c.hirer_id,
        "provider_id": c.provider_id,
        "title": c.title,
        "scope_of_work": c.scope_of_work,
        "agreed_amount": float(c.agreed_amount),
        "currency": c.currency,
        "start_date": c.start_date.isoformat() if c.start_date else None,
        "estimated_end_date": (
            c.estimated_end_date.isoformat() if c.estimated_end_date else None
        ),
        "location_text": c.location_text,
        "parish": c.parish,
        "terms_and_conditions": c.terms_and_conditions,
        "status": c.status,
        "contract_pdf_url": c.contract_pdf_url,
        "signed_pdf_url": c.signed_pdf_url,
        "generated_at": c.generated_at.isoformat(),
        "completed_at": c.completed_at.isoformat() if c.completed_at else None,
        "created_at": c.created_at.isoformat(),
        "updated_at": c.updated_at.isoformat(),
    }


def _signature_response(s: ContractSignature) -> dict:
    return {
        "id": s.id,
        "contract_id": s.contract_id,
        "signer_id": s.signer_id,
        "signer_role": s.signer_role,
        "signature_method": s.signature_method,
        "ip_address": s.ip_address,
        "user_agent": s.user_agent,
        "signed_at": s.signed_at.isoformat(),
    }


async def _get_profile_name(db: AsyncSession, user_id: str) -> str:
    """Look up display_name from profiles table, fall back to user_id."""
    result = await db.execute(
        text("SELECT display_name FROM profiles WHERE user_id = :uid"),
        {"uid": user_id},
    )
    row = result.first()
    return row[0] if row and row[0] else user_id


async def _notify_providers_for_category(
    db: AsyncSession,
    job_post: JobPost,
    hirer_name: str,
) -> None:
    """Insert notification_logs for providers matching the job's category."""
    result = await db.execute(
        text(
            "SELECT user_id FROM profiles "
            "WHERE service_category = :cat AND user_id != :hirer"
        ),
        {"cat": job_post.category, "hirer": job_post.hirer_id},
    )
    provider_rows = result.all()

    budget_str = ""
    if job_post.budget_min and job_post.budget_max:
        budget_str = f" — Budget: J${job_post.budget_min}-${job_post.budget_max}"
    elif job_post.budget_max:
        budget_str = f" — Budget: up to J${job_post.budget_max}"

    now = datetime.now(UTC)
    for row in provider_rows:
        provider_user_id = row[0]
        await db.execute(
            text(
                "INSERT INTO notification_logs "
                "(id, user_id, title, body, data, notification_type, "
                "delivered, read, sent_at) "
                "VALUES (:id, :uid, :title, :body, :data::jsonb, :ntype, "
                "false, false, :sent_at)"
            ),
            {
                "id": str(uuid.uuid4()),
                "uid": provider_user_id,
                "title": f"New Job in {job_post.category}!",
                "body": (
                    f"{hirer_name} posted: {job_post.title}{budget_str}"
                ),
                "data": f'{{"type":"job_post","job_post_id":"{job_post.id}"}}',
                "ntype": "job_post",
                "sent_at": now,
            },
        )


async def _insert_notification(
    db: AsyncSession,
    user_id: str,
    title: str,
    body: str,
    data: dict,
    notification_type: str,
) -> None:
    """Insert a single notification_logs row."""
    import json

    await db.execute(
        text(
            "INSERT INTO notification_logs "
            "(id, user_id, title, body, data, notification_type, "
            "delivered, read, sent_at) "
            "VALUES (:id, :uid, :title, :body, :data::jsonb, :ntype, "
            "false, false, :sent_at)"
        ),
        {
            "id": str(uuid.uuid4()),
            "uid": user_id,
            "title": title,
            "body": body,
            "data": json.dumps(data),
            "ntype": notification_type,
            "sent_at": datetime.now(UTC),
        },
    )


def _generate_contract_pdf(contract: Contract) -> bytes:
    """Generate a professional contract PDF using fpdf2."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=25)
    pdf.add_page()

    # Header
    pdf.set_fill_color(27, 94, 32)  # #1B5E20
    pdf.rect(0, 0, 210, 35, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_y(8)
    pdf.cell(0, 10, "JOBSY SERVICE CONTRACT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Contract ID: {contract.id}", align="C", new_x="LMARGIN", new_y="NEXT")

    # Reset text color
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(45)

    # Contract details section
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "CONTRACT DETAILS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(27, 94, 32)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 10)
    details = [
        ("Title", contract.title),
        ("Agreed Amount", f"{contract.currency} {contract.agreed_amount:,.2f}"),
        ("Start Date", str(contract.start_date) if contract.start_date else "To be agreed"),
        ("Estimated End Date", str(contract.estimated_end_date) if contract.estimated_end_date else "To be agreed"),
        ("Location", contract.location_text or "N/A"),
        ("Parish", contract.parish or "N/A"),
    ]
    for label, value in details:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 6, f"{label}:")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Scope of Work
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "SCOPE OF WORK", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, contract.scope_of_work or "")
    pdf.ln(4)

    # Terms and Conditions
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "TERMS AND CONDITIONS", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, contract.terms_and_conditions or "")
    pdf.ln(6)

    # Signature blocks
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "SIGNATURES", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "", 10)
    y = pdf.get_y()
    # Hirer signature block
    pdf.set_xy(10, y)
    pdf.cell(85, 6, "Client (Hirer):", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(85, 6, f"ID: {contract.hirer_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.cell(85, 6, "Signature: _______________________", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(85, 6, "Date: _______________________")

    # Provider signature block
    pdf.set_xy(110, y)
    pdf.cell(85, 6, "Service Provider:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(110)
    pdf.cell(85, 6, f"ID: {contract.provider_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(110)
    pdf.ln(4)
    pdf.set_x(110)
    pdf.cell(85, 6, "Signature: _______________________", new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(110)
    pdf.cell(85, 6, "Date: _______________________")

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(
        0, 5,
        "Generated by Jobsy Platform | Electronic Transactions Act, 2006",
        align="C",
    )

    return bytes(pdf.output())


async def _generate_contract_from_bid(
    db: AsyncSession,
    job_post: JobPost,
    bid: Bid,
) -> Contract:
    """Create a contract record and generate the PDF."""
    hirer_name = await _get_profile_name(db, job_post.hirer_id)
    provider_name = await _get_profile_name(db, bid.provider_id)
    now = datetime.now(UTC)
    contract_id = str(uuid.uuid4())

    scope = (
        f"Job Description:\n{job_post.description}\n\n"
        f"Provider Proposal:\n{bid.proposal}"
    )
    terms = CONTRACT_LEGAL_TEMPLATE.format(
        date=now.strftime("%B %d, %Y"),
        hirer_name=hirer_name,
        provider_name=provider_name,
        scope_of_work=scope,
        currency=bid.currency or "JMD",
        amount=f"{bid.amount:,.2f}",
        start_date=bid.available_start_date.isoformat() if bid.available_start_date else "To be agreed",
        end_date=(
            bid.available_start_date + __import__("datetime").timedelta(days=bid.estimated_duration_days)
        ).isoformat() if bid.available_start_date and bid.estimated_duration_days else "To be agreed",
        location_text=job_post.location_text or "N/A",
        contract_id=contract_id,
    )

    start_date = bid.available_start_date
    estimated_end = None
    if start_date and bid.estimated_duration_days:
        from datetime import timedelta
        estimated_end = start_date + timedelta(days=bid.estimated_duration_days)

    contract = Contract(
        id=contract_id,
        job_post_id=job_post.id,
        bid_id=bid.id,
        hirer_id=job_post.hirer_id,
        provider_id=bid.provider_id,
        title=f"Service Contract: {job_post.title}",
        scope_of_work=scope,
        agreed_amount=bid.amount,
        currency=bid.currency or "JMD",
        start_date=start_date,
        estimated_end_date=estimated_end,
        location_text=job_post.location_text,
        parish=job_post.parish,
        terms_and_conditions=terms,
        status="pending_signatures",
        generated_at=now,
        created_at=now,
        updated_at=now,
    )
    db.add(contract)
    await db.flush()
    return contract


# ===================================================================
# JOB POST ROUTES
# ===================================================================

@router.post("/", status_code=status.HTTP_201_CREATED)
async def create_job_post(
    data: JobPostCreate,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Create a new job post (hirers only)."""
    if user.get("active_role") != "user":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Only hirers can create job posts",
        )

    now = datetime.now(UTC)
    job_post = JobPost(
        id=str(uuid.uuid4()),
        hirer_id=user["user_id"],
        title=data.title,
        description=data.description,
        category=data.category,
        subcategory=data.subcategory,
        required_skills=data.required_skills,
        budget_min=data.budget_min,
        budget_max=data.budget_max,
        currency=data.currency,
        location_text=data.location_text,
        parish=data.parish,
        deadline=(
            datetime.fromisoformat(data.deadline) if data.deadline else None
        ),
        bid_deadline=(
            datetime.fromisoformat(data.bid_deadline) if data.bid_deadline else None
        ),
        status="open",
        attachments=data.attachments,
        visibility=data.visibility,
        max_bids=data.max_bids,
        created_at=now,
        updated_at=now,
    )
    db.add(job_post)
    await db.flush()

    # Notify matching providers
    hirer_name = await _get_profile_name(db, user["user_id"])
    try:
        await _notify_providers_for_category(db, job_post, hirer_name)
    except Exception:
        logger.exception("Failed to notify providers for job post %s", job_post.id)

    await publish_event("job_post.created", {
        "job_post_id": job_post.id,
        "hirer_id": user["user_id"],
        "category": data.category,
        "title": data.title,
    })

    return _job_post_response(job_post)


@router.get("/my-posts")
async def list_my_posts(
    status_filter: str | None = Query(default=None, alias="status"),
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, le=100),
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List hirer's own job posts."""
    query = select(JobPost).where(JobPost.hirer_id == user["user_id"])
    if status_filter:
        query = query.where(JobPost.status == status_filter)
    query = query.order_by(JobPost.created_at.desc()).offset((page - 1) * limit).limit(limit)
    result = await db.execute(query)
    return [_job_post_response(jp) for jp in result.scalars().all()]


@router.get("/my-bids")
async def list_my_bids(
    status_filter: str | None = Query(default=None, alias="status"),
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, le=100),
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List provider's own bids across all jobs."""
    query = select(Bid).where(Bid.provider_id == user["user_id"])
    if status_filter:
        query = query.where(Bid.status == status_filter)
    query = query.order_by(Bid.created_at.desc()).offset((page - 1) * limit).limit(limit)
    result = await db.execute(query)
    bids = result.scalars().all()

    items = []
    for b in bids:
        resp = _bid_response(b)
        # Attach job post info
        jp_result = await db.execute(
            select(JobPost).where(JobPost.id == b.job_post_id),
        )
        jp = jp_result.scalar_one_or_none()
        if jp:
            resp["job_post"] = {
                "id": jp.id,
                "title": jp.title,
                "category": jp.category,
                "status": jp.status,
                "budget_min": float(jp.budget_min) if jp.budget_min is not None else None,
                "budget_max": float(jp.budget_max) if jp.budget_max is not None else None,
            }
        items.append(resp)
    return items


@router.get("/contracts")
async def list_contracts(
    status_filter: str | None = Query(default=None, alias="status"),
    role: str | None = Query(default=None),
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, le=100),
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List user's contracts (as hirer or provider)."""
    uid = user["user_id"]
    if role == "hirer":
        query = select(Contract).where(Contract.hirer_id == uid)
    elif role == "provider":
        query = select(Contract).where(Contract.provider_id == uid)
    else:
        query = select(Contract).where(
            or_(Contract.hirer_id == uid, Contract.provider_id == uid),
        )
    if status_filter:
        query = query.where(Contract.status == status_filter)
    query = query.order_by(Contract.created_at.desc()).offset((page - 1) * limit).limit(limit)
    result = await db.execute(query)
    return [_contract_response(c) for c in result.scalars().all()]


@router.get("/contracts/{contract_id}")
async def get_contract(
    contract_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get contract detail with signatures."""
    result = await db.execute(
        select(Contract).where(Contract.id == contract_id),
    )
    contract = result.scalar_one_or_none()
    if not contract:
        raise HTTPException(status_code=404, detail="Contract not found")

    uid = user["user_id"]
    if contract.hirer_id != uid and contract.provider_id != uid:
        raise HTTPException(status_code=403, detail="Not authorized")

    resp = _contract_response(contract)

    sig_result = await db.execute(
        select(ContractSignature)
        .where(ContractSignature.contract_id == contract_id)
        .order_by(ContractSignature.signed_at),
    )
    resp["signatures"] = [_signature_response(s) for s in sig_result.scalars().all()]
    return resp


@router.get("/contracts/{contract_id}/pdf")
async def download_contract_pdf(
    contract_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Download contract as PDF."""
    result = await db.execute(
        select(Contract).where(Contract.id == contract_id),
    )
    contract = result.scalar_one_or_none()
    if not contract:
        raise HTTPException(status_code=404, detail="Contract not found")

    uid = user["user_id"]
    if contract.hirer_id != uid and contract.provider_id != uid:
        raise HTTPException(status_code=403, detail="Not authorized")

    pdf_bytes = _generate_contract_pdf(contract)
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="contract-{contract_id[:8]}.pdf"',
        },
    )


@router.post("/contracts/{contract_id}/sign")
async def sign_contract(
    contract_id: str,
    data: ContractSign,
    request: Request,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Digitally sign a contract (ETA 2006 compliant)."""
    result = await db.execute(
        select(Contract).where(Contract.id == contract_id),
    )
    contract = result.scalar_one_or_none()
    if not contract:
        raise HTTPException(status_code=404, detail="Contract not found")

    uid = user["user_id"]
    if contract.hirer_id != uid and contract.provider_id != uid:
        raise HTTPException(status_code=403, detail="Not authorized")

    # Determine signer role
    signer_role = "hirer" if uid == contract.hirer_id else "provider"

    # Check not already signed by this user
    existing = await db.execute(
        select(ContractSignature).where(
            ContractSignature.contract_id == contract_id,
            ContractSignature.signer_id == uid,
        ),
    )
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="Already signed")

    now = datetime.now(UTC)
    sig = ContractSignature(
        id=str(uuid.uuid4()),
        contract_id=contract_id,
        signer_id=uid,
        signer_role=signer_role,
        signature_data=data.signature_data,
        signature_method=data.signature_method,
        ip_address=request.client.host if request.client else None,
        user_agent=request.headers.get("user-agent", "")[:500],
        signed_at=now,
    )
    db.add(sig)

    # Update contract status
    if signer_role == "hirer":
        new_status = (
            "fully_signed" if contract.status == "provider_signed"
            else "hirer_signed"
        )
    else:
        new_status = (
            "fully_signed" if contract.status == "hirer_signed"
            else "provider_signed"
        )

    contract.status = new_status
    contract.updated_at = now
    await db.flush()

    if new_status == "fully_signed":
        # Notify both parties
        try:
            await _insert_notification(
                db, contract.hirer_id,
                "Contract Fully Signed",
                f"Contract for '{contract.title}' is fully signed — work can begin!",
                {"type": "contract", "contract_id": contract.id},
                "contract",
            )
            await _insert_notification(
                db, contract.provider_id,
                "Contract Fully Signed",
                f"Contract for '{contract.title}' is fully signed — work can begin!",
                {"type": "contract", "contract_id": contract.id},
                "contract",
            )
        except Exception:
            logger.exception("Failed to notify parties for contract %s", contract.id)

        await publish_event("contract.fully_signed", {
            "contract_id": contract.id,
            "job_post_id": contract.job_post_id,
            "hirer_id": contract.hirer_id,
            "provider_id": contract.provider_id,
        })

    resp = _contract_response(contract)
    sig_result = await db.execute(
        select(ContractSignature)
        .where(ContractSignature.contract_id == contract_id)
        .order_by(ContractSignature.signed_at),
    )
    resp["signatures"] = [_signature_response(s) for s in sig_result.scalars().all()]
    return resp


@router.get("/contracts/{contract_id}/audit-trail")
async def contract_audit_trail(
    contract_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Get signing audit trail for a contract."""
    result = await db.execute(
        select(Contract).where(Contract.id == contract_id),
    )
    contract = result.scalar_one_or_none()
    if not contract:
        raise HTTPException(status_code=404, detail="Contract not found")

    uid = user["user_id"]
    if contract.hirer_id != uid and contract.provider_id != uid:
        raise HTTPException(status_code=403, detail="Not authorized")

    sig_result = await db.execute(
        select(ContractSignature)
        .where(ContractSignature.contract_id == contract_id)
        .order_by(ContractSignature.signed_at),
    )
    return [_signature_response(s) for s in sig_result.scalars().all()]


@router.get("/stats")
async def bidding_stats(
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Bidding statistics for current user."""
    uid = user["user_id"]
    active_role = user.get("active_role", "user")

    if active_role == "provider":
        total_bids = await db.execute(
            select(func.count(Bid.id)).where(Bid.provider_id == uid),
        )
        bids_won = await db.execute(
            select(func.count(Bid.id)).where(
                Bid.provider_id == uid, Bid.is_winner.is_(True),
            ),
        )
        bids_pending = await db.execute(
            select(func.count(Bid.id)).where(
                Bid.provider_id == uid, Bid.status == "submitted",
            ),
        )
        contracts_pending = await db.execute(
            select(func.count(Contract.id)).where(
                Contract.provider_id == uid,
                Contract.status.in_(["pending_signatures", "hirer_signed", "provider_signed"]),
            ),
        )
        contracts_signed = await db.execute(
            select(func.count(Contract.id)).where(
                Contract.provider_id == uid, Contract.status == "fully_signed",
            ),
        )
        return {
            "total_bids_submitted": total_bids.scalar() or 0,
            "bids_won": bids_won.scalar() or 0,
            "bids_pending": bids_pending.scalar() or 0,
            "contracts_pending": contracts_pending.scalar() or 0,
            "contracts_signed": contracts_signed.scalar() or 0,
        }

    # Hirer stats
    total_posts = await db.execute(
        select(func.count(JobPost.id)).where(JobPost.hirer_id == uid),
    )
    active_posts = await db.execute(
        select(func.count(JobPost.id)).where(
            JobPost.hirer_id == uid, JobPost.status == "open",
        ),
    )
    total_bids_received = await db.execute(
        select(func.count(Bid.id)).where(
            Bid.job_post_id.in_(
                select(JobPost.id).where(JobPost.hirer_id == uid),
            ),
        ),
    )
    contracts_pending = await db.execute(
        select(func.count(Contract.id)).where(
            Contract.hirer_id == uid,
            Contract.status.in_(["pending_signatures", "hirer_signed", "provider_signed"]),
        ),
    )
    contracts_signed = await db.execute(
        select(func.count(Contract.id)).where(
            Contract.hirer_id == uid, Contract.status == "fully_signed",
        ),
    )
    return {
        "total_posts": total_posts.scalar() or 0,
        "active_posts": active_posts.scalar() or 0,
        "total_bids_received": total_bids_received.scalar() or 0,
        "contracts_pending": contracts_pending.scalar() or 0,
        "contracts_signed": contracts_signed.scalar() or 0,
    }


# ===================================================================
# JOB POST DETAIL / UPDATE / STATUS / DELETE
# ===================================================================

@router.get("/posts")
async def list_job_posts(
    category: str | None = Query(default=None),
    parish: str | None = Query(default=None),
    status_filter: str = Query(default="open", alias="status"),
    min_budget: float | None = Query(default=None),
    max_budget: float | None = Query(default=None),
    search: str | None = Query(default=None),
    sort_by: str = Query(default="newest"),
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, le=100),
    user: dict = Depends(get_optional_user),
    db: AsyncSession = Depends(get_db),
):
    """List job posts (public, with filters)."""
    query = select(JobPost)

    if status_filter:
        query = query.where(JobPost.status == status_filter)
    if category:
        query = query.where(JobPost.category == category)
    if parish:
        query = query.where(JobPost.parish == parish)
    if min_budget is not None:
        query = query.where(JobPost.budget_max >= min_budget)
    if max_budget is not None:
        query = query.where(JobPost.budget_min <= max_budget)
    if search:
        pattern = f"%{search}%"
        query = query.where(
            or_(
                JobPost.title.ilike(pattern),
                JobPost.description.ilike(pattern),
            ),
        )

    if sort_by == "budget_high":
        query = query.order_by(JobPost.budget_max.desc().nulls_last())
    elif sort_by == "budget_low":
        query = query.order_by(JobPost.budget_min.asc().nulls_last())
    elif sort_by == "deadline":
        query = query.order_by(JobPost.deadline.asc().nulls_last())
    else:
        query = query.order_by(JobPost.created_at.desc())

    query = query.offset((page - 1) * limit).limit(limit)
    result = await db.execute(query)
    job_posts = result.scalars().all()

    items = []
    for jp in job_posts:
        resp = _job_post_response(jp)
        # Add bid count
        bc = await db.execute(
            select(func.count(Bid.id)).where(Bid.job_post_id == jp.id),
        )
        resp["bid_count"] = bc.scalar() or 0
        items.append(resp)
    return items


@router.get("/{job_post_id}")
async def get_job_post(
    job_post_id: str,
    user: dict = Depends(get_optional_user),
    db: AsyncSession = Depends(get_db),
):
    """Get job post detail."""
    result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")

    resp = _job_post_response(jp)

    bc = await db.execute(
        select(func.count(Bid.id)).where(Bid.job_post_id == jp.id),
    )
    resp["bid_count"] = bc.scalar() or 0

    uid = user.get("user_id")
    if uid and uid != "anonymous":
        existing_bid = await db.execute(
            select(Bid.id).where(
                Bid.job_post_id == job_post_id,
                Bid.provider_id == uid,
            ),
        )
        resp["has_bid"] = existing_bid.scalar_one_or_none() is not None
    else:
        resp["has_bid"] = False

    return resp


@router.put("/{job_post_id}")
async def update_job_post(
    job_post_id: str,
    data: JobPostUpdate,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Update a job post (owner only, only if status=open)."""
    result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")
    if jp.hirer_id != user["user_id"]:
        raise HTTPException(status_code=403, detail="Not authorized")
    if jp.status != "open":
        raise HTTPException(status_code=400, detail="Can only update open job posts")

    now = datetime.now(UTC)
    if data.title is not None:
        jp.title = data.title
    if data.description is not None:
        jp.description = data.description
    if data.budget_min is not None:
        jp.budget_min = data.budget_min
    if data.budget_max is not None:
        jp.budget_max = data.budget_max
    if data.deadline is not None:
        jp.deadline = datetime.fromisoformat(data.deadline)
    if data.bid_deadline is not None:
        jp.bid_deadline = datetime.fromisoformat(data.bid_deadline)
    if data.max_bids is not None:
        jp.max_bids = data.max_bids
    jp.updated_at = now
    await db.flush()
    return _job_post_response(jp)


@router.put("/{job_post_id}/status")
async def change_job_post_status(
    job_post_id: str,
    data: JobPostStatusUpdate,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Change job post status with state machine validation."""
    result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")
    if jp.hirer_id != user["user_id"]:
        raise HTTPException(status_code=403, detail="Not authorized")

    allowed = JOB_POST_TRANSITIONS.get(jp.status, set())
    if data.status not in allowed:
        raise HTTPException(
            status_code=422,
            detail=f"Cannot transition from '{jp.status}' to '{data.status}'",
        )

    # awarded requires at least one accepted bid
    if data.status == "awarded":
        accepted = await db.execute(
            select(func.count(Bid.id)).where(
                Bid.job_post_id == job_post_id,
                Bid.status == "accepted",
            ),
        )
        if (accepted.scalar() or 0) == 0:
            raise HTTPException(
                status_code=400,
                detail="Cannot award: no accepted bids",
            )

    # cancelled only if no accepted bids
    if data.status == "cancelled":
        accepted = await db.execute(
            select(func.count(Bid.id)).where(
                Bid.job_post_id == job_post_id,
                Bid.status == "accepted",
            ),
        )
        if (accepted.scalar() or 0) > 0:
            raise HTTPException(
                status_code=400,
                detail="Cannot cancel: has accepted bids",
            )

    jp.status = data.status
    jp.updated_at = datetime.now(UTC)
    await db.flush()
    return _job_post_response(jp)


@router.delete("/{job_post_id}")
async def delete_job_post(
    job_post_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Soft delete / cancel a job post."""
    result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")
    if jp.hirer_id != user["user_id"]:
        raise HTTPException(status_code=403, detail="Not authorized")

    accepted = await db.execute(
        select(func.count(Bid.id)).where(
            Bid.job_post_id == job_post_id,
            Bid.status == "accepted",
        ),
    )
    if (accepted.scalar() or 0) > 0:
        raise HTTPException(
            status_code=400,
            detail="Cannot delete: has accepted bids",
        )

    jp.status = "cancelled"
    jp.updated_at = datetime.now(UTC)
    await db.flush()
    return {"detail": "Job post cancelled"}


# ===================================================================
# BID ROUTES
# ===================================================================

@router.post("/{job_post_id}/bids", status_code=status.HTTP_201_CREATED)
async def submit_bid(
    job_post_id: str,
    data: BidCreate,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Submit a bid on a job post (providers only)."""
    if user.get("active_role") != "provider":
        raise HTTPException(status_code=403, detail="Only providers can submit bids")

    jp_result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = jp_result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")
    if jp.status != "open":
        raise HTTPException(status_code=400, detail="Job post is not open for bidding")

    # Check bid deadline
    if jp.bid_deadline and datetime.now(UTC) > jp.bid_deadline:
        raise HTTPException(status_code=400, detail="Bid deadline has passed")

    # Check max bids
    if jp.max_bids:
        bc = await db.execute(
            select(func.count(Bid.id)).where(Bid.job_post_id == job_post_id),
        )
        if (bc.scalar() or 0) >= jp.max_bids:
            raise HTTPException(status_code=400, detail="Maximum number of bids reached")

    # Check duplicate
    existing = await db.execute(
        select(Bid).where(
            Bid.job_post_id == job_post_id,
            Bid.provider_id == user["user_id"],
        ),
    )
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="You have already bid on this job")

    now = datetime.now(UTC)
    bid = Bid(
        id=str(uuid.uuid4()),
        job_post_id=job_post_id,
        provider_id=user["user_id"],
        amount=data.amount,
        currency=data.currency,
        proposal=data.proposal,
        estimated_duration_days=data.estimated_duration_days,
        available_start_date=(
            date_type.fromisoformat(data.available_start_date)
            if data.available_start_date else None
        ),
        attachments=data.attachments,
        status="submitted",
        created_at=now,
        updated_at=now,
    )
    db.add(bid)
    await db.flush()

    # Notify hirer
    try:
        await _insert_notification(
            db, jp.hirer_id,
            f"New Bid on {jp.title}",
            f"A provider submitted a bid of {data.currency} {data.amount:,.2f}",
            {"type": "bid", "job_post_id": job_post_id, "bid_id": bid.id},
            "bid",
        )
    except Exception:
        logger.exception("Failed to notify hirer for bid %s", bid.id)

    await publish_event("bid.submitted", {
        "bid_id": bid.id,
        "job_post_id": job_post_id,
        "provider_id": user["user_id"],
        "hirer_id": jp.hirer_id,
        "amount": str(data.amount),
    })

    return _bid_response(bid)


@router.get("/{job_post_id}/bids")
async def list_bids(
    job_post_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """List bids for a job post. Hirer sees all; provider sees own."""
    jp_result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = jp_result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")

    uid = user["user_id"]
    query = select(Bid).where(Bid.job_post_id == job_post_id)
    if jp.hirer_id != uid:
        # Provider can only see their own bid
        query = query.where(Bid.provider_id == uid)

    query = query.order_by(Bid.created_at.desc())
    result = await db.execute(query)
    bids = result.scalars().all()

    items = []
    for b in bids:
        resp = _bid_response(b)
        # Attach provider profile info
        profile_result = await db.execute(
            text(
                "SELECT display_name, avatar_url, parish "
                "FROM profiles WHERE user_id = :uid"
            ),
            {"uid": b.provider_id},
        )
        profile = profile_result.first()
        if profile:
            resp["provider_display_name"] = profile[0]
            resp["provider_avatar_url"] = profile[1]
            resp["provider_parish"] = profile[2]

        # Rating info
        rating_result = await db.execute(
            text(
                "SELECT avg_rating, total_reviews FROM reputation_metrics "
                "WHERE user_id = :uid"
            ),
            {"uid": b.provider_id},
        )
        rating = rating_result.first()
        if rating:
            resp["provider_rating_avg"] = float(rating[0]) if rating[0] else 0
            resp["provider_review_count"] = rating[1] or 0
        else:
            resp["provider_rating_avg"] = 0
            resp["provider_review_count"] = 0

        items.append(resp)
    return items


@router.put("/{job_post_id}/bids/{bid_id}")
async def update_bid(
    job_post_id: str,
    bid_id: str,
    data: BidUpdate,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Update a bid (provider only, only if status=submitted)."""
    result = await db.execute(
        select(Bid).where(Bid.id == bid_id, Bid.job_post_id == job_post_id),
    )
    bid = result.scalar_one_or_none()
    if not bid:
        raise HTTPException(status_code=404, detail="Bid not found")
    if bid.provider_id != user["user_id"]:
        raise HTTPException(status_code=403, detail="Not authorized")
    if bid.status != "submitted":
        raise HTTPException(status_code=400, detail="Can only update submitted bids")

    now = datetime.now(UTC)
    if data.amount is not None:
        bid.amount = data.amount
    if data.proposal is not None:
        bid.proposal = data.proposal
    if data.estimated_duration_days is not None:
        bid.estimated_duration_days = data.estimated_duration_days
    if data.available_start_date is not None:
        bid.available_start_date = date_type.fromisoformat(data.available_start_date)
    if data.attachments is not None:
        bid.attachments = data.attachments
    bid.updated_at = now
    await db.flush()
    return _bid_response(bid)


@router.put("/{job_post_id}/bids/{bid_id}/status")
async def change_bid_status(
    job_post_id: str,
    bid_id: str,
    data: BidStatusUpdate,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Change bid status. Hirer: shortlist/accept/reject. Provider: withdraw."""
    result = await db.execute(
        select(Bid).where(Bid.id == bid_id, Bid.job_post_id == job_post_id),
    )
    bid = result.scalar_one_or_none()
    if not bid:
        raise HTTPException(status_code=404, detail="Bid not found")

    jp_result = await db.execute(
        select(JobPost).where(JobPost.id == job_post_id),
    )
    jp = jp_result.scalar_one_or_none()
    if not jp:
        raise HTTPException(status_code=404, detail="Job post not found")

    uid = user["user_id"]
    now = datetime.now(UTC)

    # Provider withdrawal
    if uid == bid.provider_id:
        allowed = BID_PROVIDER_TRANSITIONS.get(bid.status, set())
        if data.status not in allowed:
            raise HTTPException(
                status_code=422,
                detail=f"Cannot transition from '{bid.status}' to '{data.status}'",
            )
        bid.status = data.status
        bid.updated_at = now
        await db.flush()
        return _bid_response(bid)

    # Hirer actions
    if uid != jp.hirer_id:
        raise HTTPException(status_code=403, detail="Not authorized")

    allowed = BID_HIRER_TRANSITIONS.get(bid.status, set())
    if data.status not in allowed:
        raise HTTPException(
            status_code=422,
            detail=f"Cannot transition from '{bid.status}' to '{data.status}'",
        )

    if data.hirer_note is not None:
        bid.hirer_note = data.hirer_note

    bid.status = data.status
    bid.updated_at = now

    if data.status == "accepted":
        bid.is_winner = True
        await db.flush()

        # Auto-reject all other bids
        await db.execute(
            update(Bid)
            .where(
                Bid.job_post_id == job_post_id,
                Bid.id != bid_id,
                Bid.status.in_(["submitted", "shortlisted"]),
            )
            .values(status="rejected", updated_at=now),
        )

        # Set job post to awarded
        jp.status = "awarded"
        jp.updated_at = now

        # Generate contract
        contract = await _generate_contract_from_bid(db, jp, bid)
        await db.flush()

        # Notify provider: bid accepted
        try:
            await _insert_notification(
                db, bid.provider_id,
                f"Bid Accepted: {jp.title}",
                "Your bid was accepted! A contract has been generated for signing.",
                {"type": "bid", "job_post_id": jp.id, "bid_id": bid.id},
                "bid",
            )
            # Notify both: contract ready
            for party_id in [jp.hirer_id, bid.provider_id]:
                await _insert_notification(
                    db, party_id,
                    "Contract Ready to Sign",
                    f"Your contract for '{jp.title}' is ready for digital signing.",
                    {"type": "contract", "contract_id": contract.id},
                    "contract",
                )
        except Exception:
            logger.exception("Failed to notify parties for accepted bid %s", bid.id)

        await publish_event("bid.accepted", {
            "bid_id": bid.id,
            "job_post_id": jp.id,
            "provider_id": bid.provider_id,
            "hirer_id": jp.hirer_id,
        })
        await publish_event("contract.generated", {
            "contract_id": contract.id,
            "job_post_id": jp.id,
            "hirer_id": jp.hirer_id,
            "provider_id": bid.provider_id,
        })
    else:
        await db.flush()

    return _bid_response(bid)
